export enum ROUTES {
  ROOT = '',
  APP = 'app',
  LOGIN = 'login',
  REGISTER = 'register',
  RECOVER_PASSWORD = 'recover-password',
  RESET_PASSWORD = 'reset-password',
  USERS = 'users',
  HOME = 'home',
  STOCK = 'stock',
  PRODUCTS = 'products',
  SUPPLIERS = 'suppliers',
  SETTINGS = 'settings',
  ANALYTICS = 'analytics',
  TEST = 'test',
  WAREHOUSES = 'warehouses',
  CANTEENS = 'canteens',
  ORDERS = 'orders',
  DELIVERIES = 'deliveries',
  ORDER_ID = ':orderId',
  VENDOR_ID = ':vendorId',
  ANY = '*'
};

export enum URLS_TO {
  ROOT = '/',
  LOGIN = '/login',
  REGISTER = '/register',
  RECOVER_PASSWORD = '/recover-password',
  RESET_PASSWORD = '/reset-password',
  USERS = '/app/users',
  HOME = '/app/home',
  STOCK = '/app/stock',
  STOCK_WAREHOUSES = '/app/stock/warehouses',
  STOCK_CANTEENS = '/app/stock/canteens',
  PRODUCTS = '/app/products',
  SUPPLIERS = '/app/suppliers',
  SUPPLIERS_ORDERS = '/app/suppliers/orders',
  SUPPLIERS_SUPPLIERS = '/app/suppliers/suppliers',
  SUPPLIERS_DELIVERIES = '/app/suppliers/deliveries',
  SETTINGS = '/app/settings',
  ANALYTICS = '/app/analytics',
  TEST = '/app/test'
};